In [241]:
import pandas as pd
import matplotlib.pyplot as plt

In [242]:
df= pd.read_excel("../raw_data/Bank_Cust_Sub.xlsx")
df.head()

,Customer_ID,Age,Job,Marital_Status,Education,Annual_Income,Credit_Score,Account_Balance,Housing_Loan,Personal_Loan,Contacted_Before,Campaign_Count,Months_With_Bank,Subscribed
0,CUST_02526,43.0,Self-employed,Married,Not Graduate,1069085.0,741.0,50353.0,Yes,No,No,4.0,84.0,No
1,CUST_02923,34.0,Services,Single,Graduate,278319.0,710.0,86208.0,No,No,No,7.0,73.0,No
2,CUST_00890,55.0,Management,Married,Not Graduate,614943.0,746.0,0.0,Yes,Yes,Yes,3.0,1.0,No
3,CUST_00658,46.0,Admin,Divorced,Graduate,234428.0,675.0,245948.0,No,No,No,3.0,175.0,No
4,CUST_04317,49.0,Admin,Divorced,Graduate,NaN,632.0,158872.0,No,No,Yes,3.0,51.0,No

In [243]:
df.drop(columns="Customer_ID", inplace=True)
df.duplicated().sum()

np.int64(30)

In [244]:
df.drop_duplicates(inplace=True)

In [245]:
df.duplicated().sum()

np.int64(0)

In [246]:
numeric_cols = [
    "Age",
    "Annual_Income",
    "Credit_Score",
    "Account_Balance",
    "Campaign_Count",
    "Months_With_Bank"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df[col] = df[col].fillna(df[col].median())
    df[col]=df[col].astype(int)

In [247]:
# df['Age']=df['Age'].fillna(df['Age'].mean())
# df['Annual_Income']=df['Annual_Income'].fillna(df['Annual_Income'].mean())
# df['Credit_Score']=df['Credit_Score'].fillna(df['Credit_Score'].mean())
# df['Account_Balance']=df['Account_Balance'].fillna(df['Account_Balance'].median())

In [248]:
# df['Annual_Income']=df['Annual_Income'].astype(int)
# df['Age']=df['Age'].astype(int)
# df['Account_Balance']=df['Account_Balance'].astype(int)

In [249]:
col_cat=["Job", "Education", "Housing_Loan", "Personal_Loan", "Contacted_Before" ]

for col in col_cat:
    df[col]=df[col].str.strip().str.title()
    df[col]=df[col].fillna(df[col].mode()[0])
df.isna().sum()

Age                 0
Job                 0
Marital_Status      0
Education           0
Annual_Income       0
Credit_Score        0
Account_Balance     0
Housing_Loan        0
Personal_Loan       0
Contacted_Before    0
Campaign_Count      0
Months_With_Bank    0
Subscribed          0
dtype: int64

In [250]:
# for col in col_cat:
#     print(col)
#     print(df[col].unique())
#     print()

In [251]:
df["Age"].describe()

count    5000.000000
mean       39.579600
std        11.022956
min        -3.000000
25%        32.000000
50%        39.000000
75%        47.000000
max       150.000000
Name: Age, dtype: float64

In [252]:
df[df['Age']<18]
# df[df['Age']>100]

,Age,Job,Marital_Status,Education,Annual_Income,Credit_Score,Account_Balance,Housing_Loan,Personal_Loan,Contacted_Before,Campaign_Count,Months_With_Bank,Subscribed
2048,-3,Technician,Married,Graduate,665996,705,36454,Yes,Yes,Yes,4,119,Yes
3700,5,Management,Single,Graduate,582770,586,23872,Yes,No,No,3,115,No

In [253]:
df= df[(df['Age'] >=18 ) & (df['Age'] <= 100)]

In [254]:
df.describe()

,Age,Annual_Income,Credit_Score,Account_Balance,Campaign_Count,Months_With_Bank
count,4996.000000,4.996000e+03,4996.000000,4.996000e+03,4996.000000,4996.000000
mean,39.556845,6.490002e+05,689.455965,9.930044e+04,3.356685,73.170136
std,10.828861,6.540326e+05,69.293886,3.314609e+05,2.155998,46.762967
min,18.000000,5.000000e+03,100.000000,-1.000000e+04,-2.000000,-5.000000
25%,32.000000,3.821620e+05,643.000000,2.168100e+04,2.000000,39.000000
50%,39.000000,5.531070e+05,689.000000,8.347100e+04,3.000000,73.000000
75%,47.000000,7.867550e+05,735.000000,1.430078e+05,4.000000,103.000000
max,75.000000,3.000000e+07,999.000000,2.000000e+07,100.000000,1000.000000

In [255]:
# col_num=["Age", "Annual_Income", "Credit_Score",
#  "Account_Balance", "Campaign_Count", "Months_With_Bank"]

# for col in col_num:

#     Q1=df[col].quantile(0.25)
#     Q3=df[col].quantile(0.75)

#     IQR = Q3 - Q1

#     lower = Q1 - 1.5*IQR
#     upper = Q3 + 1.5*IQR

#     outliers = df[(df[col] < lower) |  (df[col] > upper)]

#     print(outliers)

In [ ]:
# df.to_csv("../clean_data/cleaned_data.csv")